name: notification_reader
description: Read Notification in Your Flutter Application.
version: 1.1.1
homepage: https://github.com/flutterbuddy1/Notification-reader-flutter-plugin

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.fluttterbuddy.notification_reader
        pluginClass: NotificationReaderPlugin